server:
  port: 8090
spring:
  application:
    name: config-eureka-server-demo
eureka:
  instance:
    instance-id: config-eureka-server-8090
    hostname: loalhost
  client:
    # 是否将自己注册到EurekaServer上，默认为true。false表示自己不进行服务注册
    register-with-eureka: false
    # 是否从其他EurekaServer获取注册信息，默认为true。单节点不需要同步其他EurekaServer服务节点的数据，设置为false
    fetch-registry: false
    # 设置EurekaServer的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/