# 服务端口
server:
  port: 6063
# Eureka
eureka:
  instance:
    hostname: zuul-gateway-ha-6063
    # Eureka注册中心页面中status展示的值
    instance-id: zuul-gateway-ha-6063
    # Eureka注册中心页面中左下角info优先展示ip端口
    prefer-ip-address: true



