# 服务端口
server:
  port: 9090
spring:
  application:
    name: microservice-consumer-ribbon-demo
eureka:
  instance:
    instance-id: consumer-ribbon-9090
    prefer-ip-address: true
  client:
    # 不注册到EurekaServer中
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7070/eureka/
