server:
  port: 9080
spring:
  application:
    name: microservice-cousumer-feign-demo
eureka:
  instance:
    instance-id: cousumer-feign-9080
    prefer-ip-address: true
  client:
    # 不注册到EurekaServer中
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7070/eureka/