server:
  port: 9070
spring:
  application:
    name: microservice-discovery-demo
eureka:
  instance:
    hostname: discover-9070
    instance-id: discover-9070
    prefer-ip-address: true
  client:
    service-url:
      # 单机
      defaultZone: http://localhost:7070/eureka/
