# 服务端口
server:
  port: 8083
# Eureka
eureka:
  instance:
    hostname: provider-ha-8083
    # Eureka注册中心页面中status展示的值
    instance-id: provider-ha-8083
    # Eureka注册中心页面中左下角info优先展示ip端口
    prefer-ip-address: true



